apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower-app-deployment
  namespace: test-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: test-container
          image: muralisocial123/flower-sample:v2.0
          ports:
            - containerPort: 3015
---
apiVersion: v1
kind: Service
metadata:
  name: flower-app-service
  namespace: test-ns  
spec:
  selector:
    app: web  
  ports:
    - protocol: TCP
      port: 3016 #Service Port - On which port you want to expose the application        
      targetPort: 3015  # On Which Port your application is running inside the container
  type: LoadBalancer     